function cleanText(v){return(v||'').replace(/\s+/g,' ').trim().slice(0,140)}
function encodeMessage(t){return encodeURIComponent(t).replace(/%20/g,'+')}
function trackEvent(n,p){p=p||{};p.page_path=location.pathname;p.page_title=document.title||'';try{if(typeof gtag==='function')gtag('event',n,p)}catch(e){}try{if(typeof clarity==='function')clarity('event',n)}catch(e){}try{if(typeof fbq==='function'&&(n.includes('whatsapp')||n.includes('call')||n.includes('sms')||n.includes('contact')))fbq('track','Contact',{content_name:document.title||'',page_path:location.pathname})}catch(e){}}
(function(){if(window.clarity||window.__mathildeClarityLoaded)return;window.__mathildeClarityLoaded=true;(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src='https://www.clarity.ms/tag/'+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,'clarity','script','whwpwxoeln')})();
(function(){
  if(window.__mathildeT2Ux)return;window.__mathildeT2Ux=true;
  var isT2=location.pathname.indexOf('appartement-t2-punaauia-pk11.html')!==-1;
  var css=[
    ".t2-landing-page a.cta-call{display:none!important}.t2-landing-page .t2-sticky-actions{display:none!important}",
    "@media(max-width:860px){.t2-landing-page .t2-gallery{padding-bottom:0!important}.t2-landing-page .t2-gallery-action{position:static!important;inset:auto!important;width:calc(100% - 20px)!important;max-width:none!important;margin:8px auto 10px!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;padding:8px!important;border:1px solid rgba(255,255,255,.62)!important;border-radius:18px!important;background:linear-gradient(135deg,rgba(23,20,18,.94),rgba(42,33,27,.90))!important;box-shadow:0 10px 28px rgba(35,24,17,.16)!important}.t2-landing-page .t2-gallery-action [data-gallery-caption]{display:none!important}.t2-landing-page .t2-gallery-action .cta-gallery,.t2-landing-page .t2-gallery-action .cta-gallery-call{width:100%!important;min-height:38px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:8px 10px!important;border-radius:999px!important;font-size:12px!important;font-weight:900!important;line-height:1!important;text-decoration:none!important}.t2-landing-page .t2-gallery-action .cta-gallery-call{background:rgba(255,255,255,.96)!important;color:#171412!important}.t2-landing-page .t2-gallery-action .cta-gallery{background:var(--kw-red,#c8102e)!important;color:#fff!important}}",
    ".t2-question-helper{position:fixed;left:11px;bottom:18px;z-index:96;width:calc((100vw - 32px)/2);max-width:244px;font-family:inherit;opacity:0;transform:translateY(8px) scale(.98);pointer-events:none;transition:opacity .28s ease,transform .28s ease}.t2-question-helper.is-visible{opacity:1;transform:translateY(0) scale(1);pointer-events:auto}",
    ".t2-helper-launcher{width:100%;min-height:48px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:8px 10px;border:1px solid rgba(255,255,255,.68);border-radius:999px;background:#171412;color:#fff;box-shadow:0 16px 42px rgba(35,24,17,.18);backdrop-filter:blur(14px);cursor:pointer;font-weight:900}.t2-helper-avatar{width:30px;height:30px;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;background:#1877f2;color:#fff;font-size:15px;flex:0 0 auto}.t2-helper-text{display:grid;gap:1px;text-align:left}.t2-helper-text strong{font-size:11.5px;line-height:1.1}.t2-helper-text span{font-size:10px;line-height:1.1;color:rgba(255,255,255,.78);font-weight:800}",
    ".t2-helper-panel,.t2-contact-popover{display:none;position:absolute;left:0;bottom:58px;width:min(342px,calc(100vw - 22px));border-radius:22px;overflow:hidden;background:#fff;border:1px solid #e5e7eb;box-shadow:0 18px 46px rgba(15,23,42,.14)}.is-open .t2-helper-panel,.t2-contact-popover.is-open{display:block}.t2-contact-popover{position:fixed;z-index:120;bottom:auto;left:auto}.t2-helper-head{display:flex;justify-content:space-between;gap:10px;padding:12px 14px;background:#fff;color:#1c1e21;border-bottom:1px solid #edf0f2}.t2-helper-head strong{display:block;font-size:14px;line-height:1.1}.t2-helper-head span{display:block;margin-top:3px;font-size:11px;color:#65676b;font-weight:800;line-height:1.25}.t2-helper-close{border:0;background:#f0f2f5;color:#1c1e21;border-radius:999px;width:28px;height:28px;cursor:pointer;font-weight:900}",
    ".t2-helper-body{padding:11px;background:#fff}.t2-helper-bubble{display:inline-block;max-width:92%;padding:10px 12px;border-radius:18px 18px 18px 6px;background:#f0f2f5;color:#1c1e21;font-size:12px;line-height:1.35;font-weight:700}.t2-helper-chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.t2-helper-chips[hidden]{display:none!important}.t2-helper-chip,.t2-helper-more{border:1px solid #e4e6eb;background:#f7f8fa;color:#1c1e21;border-radius:999px;min-height:32px;padding:6px 10px;font-weight:900;font-size:11.5px;cursor:pointer}.t2-helper-more{border-color:transparent;background:transparent;color:#1877f2;padding-left:2px}.t2-helper-answer{margin-top:10px;display:none}.t2-helper-answer.is-visible{display:block}.t2-helper-answer p{max-width:92%;margin:0 0 0 auto;padding:10px 12px;border-radius:18px 18px 6px 18px;background:#e7f3ff;color:#0b2b4c;border:1px solid rgba(0,132,255,.12);font-size:12px;line-height:1.38;font-weight:700;box-shadow:0 3px 10px rgba(0,132,255,.08)}",
    ".t2-helper-cta,.t2-contact-options{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.t2-helper-cta a,.t2-contact-options a{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:7px 9px;border-radius:999px;text-decoration:none;font-weight:900;font-size:12px}.t2-helper-cta .whatsapp,.t2-contact-options .whatsapp{background:var(--kw-red,#c8102e);color:#fff}.t2-helper-cta .call,.t2-contact-options .call{background:#171412;color:#fff}.t2-contact-options .sms{background:#fff;color:#171412;border:1px solid rgba(35,24,17,.14);grid-column:1/-1}.t2-contact-popover .t2-contact-options{grid-template-columns:1fr}.t2-contact-popover .t2-contact-options .sms{grid-column:auto}"
  ].join('\n');
  var st=document.createElement('style');st.id='t2-messenger-refined-style';st.textContent=css;document.head.appendChild(st);
  function addHelpers(){
    if(!isT2)return;
    var wa='https://wa.me/33782475958?text='+encodeMessage('Ia ora na Mathilde, j’ai une question sur le T2 à Punaauia PK11. Peux-tu m’aider à voir s’il correspond à mon projet ?');
    var sms='sms:+68988078247?body='+encodeURIComponent('Ia ora na Mathilde, j’ai une question sur le T2 à Punaauia PK11.');
    var tel='tel:+68988078247';
    var a={prix:'Le T2 est affiché à 39,5M XPF. Pour savoir s’il correspond à ton projet et à ton financement, le plus simple est d’échanger directement avec Mathilde.',surface:'Il fait 59,93 m² habitables, avec une varangue de 14,63 m².',louer:'La location saisonnière type Airbnb n’est pas autorisée. En revanche, la location longue durée est possible et fonctionne très bien sur ce secteur.',localisation:'Le bien est à Punaauia PK11. Pour les détails précis de localisation et de résidence, Mathilde te les donne directement au téléphone.',video:'La vidéo est envoyée sur demande après un échange rapide, pour vérifier que le bien correspond vraiment à ton projet.',visite:'Oui, les visites sont organisées sur demande. Le mieux est de contacter Mathilde pour valider le projet et les disponibilités.',investir:'Le bien peut être intéressant en longue durée selon ton financement et ton objectif. Mathilde peut t’aider à vérifier la cohérence du projet.',charges:'Bonne question : pour les charges et les éléments de copropriété, Mathilde préfère te répondre directement avec les informations à jour.'};
    var contactPanel=document.createElement('div');contactPanel.className='t2-contact-popover';contactPanel.innerHTML='<div class="t2-helper-head"><div><strong>Comment tu préfères me contacter ?</strong><span>WhatsApp, SMS ou appel direct.</span></div><button class="t2-helper-close" type="button" data-contact-close>×</button></div><div class="t2-helper-body"><div class="t2-helper-bubble">Je réponds plus vite sur WhatsApp, mais tu peux aussi appeler ou envoyer un SMS.</div><div class="t2-contact-options"><a class="whatsapp" href="'+wa+'" target="_blank" rel="noopener" data-event="click_t2_contact_whatsapp">📱 WhatsApp</a><a class="sms" href="'+sms+'" data-event="click_t2_contact_sms">💬 SMS</a><a class="call" href="'+tel+'" data-event="click_t2_contact_call">📞 Appeler</a></div></div>';document.body.appendChild(contactPanel);contactPanel.querySelector('[data-contact-close]').onclick=function(){contactPanel.classList.remove('is-open')};
    function openContact(btn){var r=btn.getBoundingClientRect(),w=Math.min(342,innerWidth-22);contactPanel.style.left=Math.max(11,Math.min(r.left,innerWidth-w-11))+'px';contactPanel.style.top=Math.max(12,r.bottom+8)+'px';if(r.bottom+280>innerHeight)contactPanel.style.top=Math.max(12,r.top-280)+'px';contactPanel.classList.add('is-open');trackEvent('open_t2_contact_options',{event_category:'contact',source:cleanText(btn.textContent)})}
    document.querySelectorAll('a.cta-whatsapp:not(.cta-gallery):not(.cta-visite),a.cta-gallery-call').forEach(function(btn){btn.textContent='✉️ Me contacter';btn.setAttribute('href','#contact-options');btn.removeAttribute('target');btn.removeAttribute('rel');btn.addEventListener('click',function(e){e.preventDefault();openContact(btn)})});
    document.querySelectorAll('.cta-gallery').forEach(function(btn){btn.textContent='📱 Demander la visite virtuelle'});
    if(!document.querySelector('[data-t2-question-helper]')){var q=document.createElement('div');q.className='t2-question-helper';q.setAttribute('data-t2-question-helper','true');q.innerHTML='<button class="t2-helper-launcher" type="button" data-open><span class="t2-helper-avatar">💬</span><span class="t2-helper-text"><strong>Question ?</strong><span>Réponse rapide</span></span></button><div class="t2-helper-panel"><div class="t2-helper-head"><div><strong>Ia ora na 👋</strong><span>Choisis une question. Pour les détails précis, Mathilde te répond directement.</span></div><button class="t2-helper-close" type="button" data-close>×</button></div><div class="t2-helper-body"><div class="t2-helper-bubble">Je peux te donner les infos principales sans alourdir la page.</div><div class="t2-helper-chips"><button class="t2-helper-chip" data-q="prix">Prix</button><button class="t2-helper-chip" data-q="surface">Surface</button><button class="t2-helper-chip" data-q="localisation">Localisation</button><button class="t2-helper-chip" data-q="louer">Louer ?</button><button class="t2-helper-chip" data-q="video">Vidéo</button><button class="t2-helper-more" data-more>+ autres</button></div><div class="t2-helper-chips" hidden data-extra><button class="t2-helper-chip" data-q="visite">Visiter</button><button class="t2-helper-chip" data-q="investir">Investir</button><button class="t2-helper-chip" data-q="charges">Charges</button></div><div class="t2-helper-answer" data-answer></div></div></div>';document.body.appendChild(q);q.querySelector('[data-open]').onclick=function(){q.classList.toggle('is-open');trackEvent(q.classList.contains('is-open')?'open_t2_helper_bubble':'close_t2_helper_bubble',{event_category:'buyer_lead'})};q.querySelector('[data-close]').onclick=function(){q.classList.remove('is-open')};q.querySelector('[data-more]').onclick=function(){var e=q.querySelector('[data-extra]'),h=e.hasAttribute('hidden');if(h)e.removeAttribute('hidden');else e.setAttribute('hidden','');this.textContent=h?'- moins':'+ autres'};q.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){var k=b.getAttribute('data-q'),box=q.querySelector('[data-answer]');box.innerHTML='<p>'+a[k]+'</p><div class="t2-helper-cta"><a class="whatsapp" href="'+wa+'" target="_blank" rel="noopener" data-event="click_t2_helper_whatsapp">📱 WhatsApp</a><a class="call" href="'+tel+'" data-event="click_t2_helper_call">📞 Appeler</a></div>';box.classList.add('is-visible');trackEvent('click_t2_helper_question',{event_category:'buyer_lead',question:k})}})}
    setTimeout(function(){document.querySelectorAll('.t2-question-helper').forEach(function(el){el.classList.add('is-visible')});trackEvent('view_t2_question_helper',{event_category:'buyer_lead'})},900)
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addHelpers);else addHelpers();
})();
document.addEventListener('click',function(e){var t=e.target.closest('[data-event]');if(t)trackEvent(t.getAttribute('data-event'),{link_text:cleanText(t.textContent),link_url:t.href||''})});
document.addEventListener('DOMContentLoaded',function(){trackEvent('page_ready',{event_category:'engagement'});document.querySelectorAll('[data-t2-gallery]').forEach(function(g){var main=g.querySelector('[data-gallery-main]'),idx=g.querySelector('[data-gallery-index]'),cap=g.querySelector('[data-gallery-caption]'),thumbs=[].slice.call(g.querySelectorAll('[data-gallery-thumb]')),cur=0;if(!main||!thumbs.length)return;function show(i,src){cur=(i+thumbs.length)%thumbs.length;var th=thumbs[cur];main.style.opacity='.55';setTimeout(function(){main.src=th.getAttribute('data-full');main.alt=th.getAttribute('data-alt')||'';main.style.opacity='1'},80);if(idx)idx.textContent=String(cur+1);if(cap)cap.textContent=th.getAttribute('data-caption')||'';thumbs.forEach(function(x,n){x.classList.toggle('is-active',n===cur)});if(src)trackEvent('view_t2_gallery_photo',{event_category:'buyer_lead',gallery_index:cur+1,gallery_source:src})}g.querySelectorAll('[data-gallery-next]').forEach(function(b){b.addEventListener('click',function(){show(cur+1,'next')})});g.querySelectorAll('[data-gallery-prev]').forEach(function(b){b.addEventListener('click',function(){show(cur-1,'prev')})});thumbs.forEach(function(b,i){b.addEventListener('click',function(){show(i,'thumb')})})});document.querySelectorAll('.nav-toggle').forEach(function(btn){btn.addEventListener('click',function(){var nav=btn.closest('.nav'),m=nav&&nav.querySelector('.menu');if(!m)return;var o=m.classList.toggle('open');btn.setAttribute('aria-expanded',o?'true':'false');btn.textContent=o?'Fermer le menu':'Menu'})});var t2=document.querySelector('[data-t2-virtual-form]');if(t2)t2.addEventListener('submit',function(e){e.preventDefault();var d=new FormData(t2);var msg=['Ia ora na Mathilde, je souhaite recevoir les informations sur le T2 a Punaauia PK11.','','Prenom : '+(d.get('prenom')||''),'Telephone : '+(d.get('telephone')||''),'Projet : '+(d.get('projet')||''),'Message : '+(d.get('message')||''),'','Je souhaite etre recontacte pour la fiche complete, la visite virtuelle ou une visite privee.'].join('\n');trackEvent('submit_form_t2_virtual',{event_category:'buyer_lead'});location.href='https://wa.me/33782475958?text='+encodeMessage(msg)});var est=document.querySelector('[data-estimation-form]');if(est)est.addEventListener('submit',function(e){e.preventDefault();var d=new FormData(est);var msg=['Ia ora na Mathilde, je souhaite une estimation gratuite de mon bien a Tahiti.','','Nom : '+(d.get('nom')||''),'Telephone : '+(d.get('telephone')||''),'Email : '+(d.get('email')||''),'Commune : '+(d.get('commune')||''),'Type de bien : '+(d.get('type')||''),'Objectif : '+(d.get('objectif')||''),'Surface approximative : '+(d.get('surface')||''),'Secteur / repere : '+(d.get('adresse')||''),'Message : '+(d.get('message')||'')].join('\n');trackEvent('submit_form_estimation',{event_category:'seller_lead'});location.href='https://wa.me/33782475958?text='+encodeMessage(msg)})});