function cleanText(v){return(v||'').replace(/\s+/g,' ').trim().slice(0,140)}
function encodeMessage(t){return encodeURIComponent(t).replace(/%20/g,'+')}
function trackEvent(n,p){p=p||{};p.page_location=location.href;p.page_path=location.pathname;p.page_title=document.title||'';try{if(typeof gtag==='function')gtag('event',n,p)}catch(e){}try{if(typeof clarity==='function')clarity('event',n)}catch(e){}try{if(typeof fbq==='function'&&(n.includes('whatsapp')||n.includes('call')||n.includes('sms')||n.includes('contact')))fbq('track','Contact',{content_name:document.title||'',page_path:location.pathname})}catch(e){}}
(function(){if(window.clarity||window.__mathildeClarityLoaded)return;window.__mathildeClarityLoaded=true;(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src='https://www.clarity.ms/tag/'+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,'clarity','script','whwpwxoeln')})();
(function(){
  if(window.__mathildeT2Ux)return;window.__mathildeT2Ux=true;
  var isT2=location.pathname.indexOf('appartement-t2-punaauia-pk11.html')!==-1;
  var css=[
    ".t2-landing-page a.cta-call{display:none!important}.t2-landing-page .t2-sticky-actions,.t2-landing-page .mk-contact-widget{display:none!important}",
    ".t2-landing-page .t2-process,.t2-landing-page .t2-inline-cta,.t2-landing-page #visite-virtuelle .t2-anchor-cta,.t2-landing-page #faq-t2 .section-cta,.t2-landing-page main>section:has(.contact-strip){display:none!important}",
    ".t2-landing-page #visite-virtuelle{padding-top:34px!important}.t2-landing-page #t2-formulaire-visite{margin-top:0!important}.t2-landing-page .t2-form-grid{border-top:1px solid rgba(35,24,17,.08);padding-top:28px}.t2-landing-page #faq-t2{border-top:1px solid rgba(35,24,17,.08)}",
    "@media(max-width:860px){.t2-landing-page{padding-bottom:88px}.t2-landing-page .t2-gallery{padding-bottom:0!important}.t2-landing-page .t2-gallery-action{position:static!important;inset:auto!important;width:calc(100% - 20px)!important;max-width:none!important;margin:8px auto 10px!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;padding:8px!important;border:1px solid rgba(255,255,255,.62)!important;border-radius:18px!important;background:linear-gradient(135deg,rgba(23,20,18,.94),rgba(42,33,27,.90))!important;box-shadow:0 10px 28px rgba(35,24,17,.16)!important}.t2-landing-page .t2-gallery-action [data-gallery-caption]{display:none!important}.t2-landing-page .t2-gallery-action .cta-gallery,.t2-landing-page .t2-gallery-action .cta-gallery-call{width:100%!important;min-height:38px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:8px 10px!important;border-radius:999px!important;font-size:12px!important;font-weight:900!important;line-height:1!important;text-decoration:none!important}.t2-landing-page .t2-gallery-action .cta-gallery-call{background:rgba(255,255,255,.96)!important;color:#171412!important}.t2-landing-page .t2-gallery-action .cta-gallery{background:var(--kw-red,#c8102e)!important;color:#fff!important}}",
    ".t2-question-helper{position:fixed;left:11px;bottom:18px;z-index:96;width:calc((100vw - 32px)/2);max-width:244px;font-family:inherit;opacity:0;transform:translateY(8px) scale(.98);pointer-events:none;transition:opacity .28s ease,transform .28s ease}.t2-question-helper.is-visible{opacity:1;transform:translateY(0) scale(1);pointer-events:auto}",
    ".t2-sticky-contact{position:fixed;left:12px;right:12px;bottom:12px;z-index:96;min-height:50px;display:inline-flex!important;align-items:center;justify-content:center;gap:8px;padding:9px 14px;border:1px solid rgba(255,255,255,.68);border-radius:999px;background:var(--kw-red,#c8102e);color:#fff;text-decoration:none;box-shadow:0 16px 42px rgba(35,24,17,.18);backdrop-filter:blur(14px);font-weight:900;font-size:14px;opacity:0;transform:translateY(8px) scale(.98);pointer-events:none;transition:opacity .28s ease,transform .28s ease}.t2-sticky-contact.is-visible{opacity:1;transform:translateY(0) scale(1);pointer-events:auto}.t2-sticky-contact span{display:inline-flex;width:30px;height:30px;border-radius:999px;background:rgba(255,255,255,.14);align-items:center;justify-content:center;flex:0 0 auto}@media(min-width:861px){.t2-question-helper{width:220px}.t2-sticky-contact{display:none!important}}@media(max-width:860px){.t2-question-helper{display:none!important}}",
    ".t2-helper-launcher{width:100%;min-height:48px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:8px 10px;border:1px solid rgba(255,255,255,.68);border-radius:999px;background:#171412;color:#fff;box-shadow:0 16px 42px rgba(35,24,17,.18);backdrop-filter:blur(14px);cursor:pointer;font-weight:900}.t2-helper-avatar{width:30px;height:30px;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;background:#1877f2;color:#fff;font-size:15px;flex:0 0 auto}.t2-helper-text{display:grid;gap:1px;text-align:left}.t2-helper-text strong{font-size:11.5px;line-height:1.1}.t2-helper-text span{font-size:10px;line-height:1.1;color:rgba(255,255,255,.78);font-weight:800}",
    ".t2-helper-panel,.t2-contact-popover{display:none;position:absolute;left:0;bottom:58px;width:min(342px,calc(100vw - 22px));border-radius:22px;overflow:hidden;background:#fff;border:1px solid #e5e7eb;box-shadow:0 18px 46px rgba(15,23,42,.14)}.is-open .t2-helper-panel,.t2-contact-popover.is-open{display:block}.t2-contact-popover{position:fixed;z-index:120;bottom:auto;left:auto}.t2-helper-head{display:flex;justify-content:space-between;gap:10px;padding:12px 14px;background:#fff;color:#1c1e21;border-bottom:1px solid #edf0f2}.t2-helper-head strong{display:block;font-size:14px;line-height:1.1}.t2-helper-head span{display:block;margin-top:3px;font-size:11px;color:#65676b;font-weight:800;line-height:1.25}.t2-helper-close{border:0;background:#f0f2f5;color:#1c1e21;border-radius:999px;width:28px;height:28px;cursor:pointer;font-weight:900}",
    ".t2-helper-body{padding:11px;background:#fff}.t2-helper-bubble{display:inline-block;max-width:92%;padding:10px 12px;border-radius:18px 18px 18px 6px;background:#f0f2f5;color:#1c1e21;font-size:12px;line-height:1.35;font-weight:700}.t2-helper-chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.t2-helper-chips[hidden]{display:none!important}.t2-helper-chip,.t2-helper-more{border:1px solid #e4e6eb;background:#f7f8fa;color:#1c1e21;border-radius:999px;min-height:32px;padding:6px 10px;font-weight:900;font-size:11.5px;cursor:pointer}.t2-helper-more{border-color:transparent;background:transparent;color:#1877f2;padding-left:2px}.t2-helper-answer{margin-top:10px;display:none}.t2-helper-answer.is-visible{display:block}.t2-helper-answer p{max-width:92%;margin:0 0 0 auto;padding:10px 12px;border-radius:18px 18px 6px 18px;background:#e7f3ff;color:#0b2b4c;border:1px solid rgba(0,132,255,.12);font-size:12px;line-height:1.38;font-weight:700;box-shadow:0 3px 10px rgba(0,132,255,.08)}",
    ".t2-helper-cta,.t2-contact-options{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.t2-helper-cta a,.t2-contact-options a{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:7px 9px;border-radius:999px;text-decoration:none;font-weight:900;font-size:12px}.t2-helper-cta .whatsapp,.t2-contact-options .whatsapp{background:var(--kw-red,#c8102e);color:#fff}.t2-helper-cta .call,.t2-contact-options .call{background:#171412;color:#fff}.t2-contact-options .sms{background:#fff;color:#171412;border:1px solid rgba(35,24,17,.14);grid-column:1/-1}.t2-contact-popover .t2-contact-options{grid-template-columns:1fr}.t2-contact-popover .t2-contact-options .sms{grid-column:auto}",
    ".t2-scroll-top{position:fixed;right:14px;top:50%;z-index:95;width:42px;height:42px;border:1px solid rgba(255,255,255,.68);border-radius:999px;background:rgba(255,255,255,.94);color:#171412;box-shadow:0 14px 36px rgba(35,24,17,.14);backdrop-filter:blur(14px);display:inline-flex;align-items:center;justify-content:center;font-size:18px;font-weight:900;cursor:pointer;opacity:0;transform:translateY(-50%) scale(.96);pointer-events:none;transition:opacity .22s ease,transform .22s ease}.t2-scroll-top.is-visible{opacity:.86;transform:translateY(-50%) scale(1);pointer-events:auto}.t2-scroll-top:hover{background:#171412;color:#fff;opacity:1}@media(max-width:860px){.t2-scroll-top{right:10px;top:56%;width:40px;height:40px;font-size:17px}}"
  ].join('\n');
  var st=document.createElement('style');st.id='t2-reduced-page-style';st.textContent=css;document.head.appendChild(st);
  function addHelpers(){
    if(!isT2)return;
    var defaultMessage='Ia ora na Mathilde, je souhaite recevoir les infos pour le T2 à Punaauia.';
    var waContact='https://wa.me/33782475958?text='+encodeMessage(defaultMessage);
    var wa=waContact;
    var sms='sms:+68988078247?body='+encodeURIComponent(defaultMessage);
    var tel='tel:+68988078247';
    var a={prix:'Le T2 est affiché à 39,5M XPF. Pour savoir s’il correspond à ton projet et à ton financement, le plus simple est d’échanger directement avec Mathilde.',surface:'Il fait 59,93 m² habitables, avec une varangue de 14,63 m².',louer:'La location saisonnière type Airbnb n’est pas autorisée. En revanche, la location longue durée est possible et fonctionne très bien sur ce secteur.',localisation:'Le bien est à Punaauia. Les informations précises sont communiquées directement après un premier échange qualifié.',video:'La vidéo est envoyée sur demande après un échange rapide, pour vérifier que le bien correspond vraiment à ton projet.',visite:'Oui, les visites sont organisées sur demande. Le mieux est de contacter Mathilde pour valider le projet et les disponibilités.',investir:'Le bien peut être intéressant en longue durée selon ton financement et ton objectif. Mathilde peut t’aider à vérifier la cohérence du projet.',charges:'Bonne question : pour les charges et les éléments de copropriété, Mathilde préfère te répondre directement avec les informations à jour.'};
    var contactPanel=document.createElement('div');contactPanel.className='t2-contact-popover';contactPanel.innerHTML='<div class="t2-helper-head"><div><strong>Comment tu préfères me contacter ?</strong><span>WhatsApp, SMS ou appel direct.</span></div><button class="t2-helper-close" type="button" data-contact-close>×</button></div><div class="t2-helper-body"><div class="t2-helper-bubble">Je réponds plus vite sur WhatsApp, mais tu peux aussi appeler ou envoyer un SMS.</div><div class="t2-contact-options"><a class="whatsapp" href="'+wa+'" target="_blank" rel="noopener" data-event="whatsapp_click_pk11">📱 WhatsApp</a><a class="sms" href="'+sms+'" data-event="sms_click_pk11">💬 SMS</a><a class="call" href="'+tel+'" data-event="call_click_pk11">📞 Appeler</a></div></div>';document.body.appendChild(contactPanel);contactPanel.querySelector('[data-contact-close]').onclick=function(){contactPanel.classList.remove('is-open')};
    function openContact(btn){var message=btn.getAttribute('data-contact-message')||defaultMessage;contactPanel.querySelector('.whatsapp').href='https://wa.me/33782475958?text='+encodeMessage(message);contactPanel.querySelector('.sms').href='sms:+68988078247?body='+encodeURIComponent(message);var r=btn.getBoundingClientRect(),w=Math.min(342,innerWidth-22);contactPanel.style.left=Math.max(11,Math.min(r.left,innerWidth-w-11))+'px';contactPanel.style.top=Math.max(12,r.bottom+8)+'px';if(r.bottom+280>innerHeight)contactPanel.style.top=Math.max(12,r.top-280)+'px';contactPanel.classList.add('is-open');trackEvent('contact_modal_open_pk11',{event_category:'contact',source:btn.getAttribute('data-contact-source')||cleanText(btn.textContent)})}
    document.querySelectorAll('a.cta-whatsapp:not(.cta-gallery):not(.cta-visite),a.cta-gallery-call').forEach(function(btn){btn.setAttribute('href','#contact-options');btn.removeAttribute('target');btn.removeAttribute('rel');btn.addEventListener('click',function(e){e.preventDefault();openContact(btn)})});
    document.querySelectorAll('.cta-gallery').forEach(function(btn){btn.textContent='📱 Demander la visite vidéo sur demande'});
    var formHead=document.querySelector('#visite-virtuelle .form-promise h2');if(formHead)formHead.textContent='Tu veux la vidéo ou programmer une visite ?';
    var formText=document.querySelector('#visite-virtuelle .form-promise p');if(formText)formText.textContent='La vidéo de visite peut être envoyée après un échange rapide, afin de te donner les informations importantes sur le bien et vérifier que cela correspond bien à ton projet.';
    var trust=document.querySelector('#visite-virtuelle .form-promise .trust-list');if(trust)trust.innerHTML='<li>Un seul point de contact : WhatsApp, SMS ou appel.</li><li>Vidéo envoyée après qualification.</li><li>Visite sur place organisée si l’appartement te plaît après la vidéo.</li>';
    if(!document.querySelector('[data-t2-question-helper]')){var q=document.createElement('div');q.className='t2-question-helper';q.setAttribute('data-t2-question-helper','true');q.innerHTML='<button class="t2-helper-launcher" type="button" data-open><span class="t2-helper-avatar">💬</span><span class="t2-helper-text"><strong>Question ?</strong><span>Réponse rapide</span></span></button><div class="t2-helper-panel"><div class="t2-helper-head"><div><strong>Ia ora na 👋</strong><span>Choisis une question. Pour les détails précis, Mathilde te répond directement.</span></div><button class="t2-helper-close" type="button" data-close>×</button></div><div class="t2-helper-body"><div class="t2-helper-bubble">Je peux te donner les infos principales sans alourdir la page.</div><div class="t2-helper-chips"><button class="t2-helper-chip" data-q="prix">Prix</button><button class="t2-helper-chip" data-q="surface">Surface</button><button class="t2-helper-chip" data-q="localisation">Localisation</button><button class="t2-helper-chip" data-q="louer">Louer ?</button><button class="t2-helper-chip" data-q="video">Vidéo</button><button class="t2-helper-more" data-more>+ autres</button></div><div class="t2-helper-chips" hidden data-extra><button class="t2-helper-chip" data-q="visite">Visiter</button><button class="t2-helper-chip" data-q="investir">Investir</button><button class="t2-helper-chip" data-q="charges">Charges</button></div><div class="t2-helper-answer" data-answer></div></div></div>';document.body.appendChild(q);q.querySelector('[data-open]').onclick=function(){q.classList.toggle('is-open');trackEvent(q.classList.contains('is-open')?'open_t2_helper_bubble':'close_t2_helper_bubble',{event_category:'buyer_lead'})};q.querySelector('[data-close]').onclick=function(){q.classList.remove('is-open')};q.querySelector('[data-more]').onclick=function(){var e=q.querySelector('[data-extra]'),h=e.hasAttribute('hidden');if(h)e.removeAttribute('hidden');else e.setAttribute('hidden','');this.textContent=h?'- moins':'+ autres'};q.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){var k=b.getAttribute('data-q'),box=q.querySelector('[data-answer]');box.innerHTML='<p>'+a[k]+'</p><div class="t2-helper-cta"><a class="whatsapp" href="'+wa+'" target="_blank" rel="noopener" data-event="click_t2_helper_whatsapp">📱 WhatsApp</a><a class="call" href="'+tel+'" data-event="click_t2_helper_call">📞 Appeler</a></div>';box.classList.add('is-visible');trackEvent('click_t2_helper_question',{event_category:'buyer_lead',question:k})}})}
    if(!document.querySelector('[data-t2-sticky-contact]')){var sticky=document.createElement('button');sticky.className='t2-sticky-contact';sticky.type='button';sticky.setAttribute('data-t2-sticky-contact','true');sticky.setAttribute('data-contact-source','sticky');sticky.setAttribute('data-contact-message',defaultMessage);sticky.innerHTML='<span>✉️</span>Recevoir les infos / visiter';document.body.appendChild(sticky);sticky.addEventListener('click',function(e){e.preventDefault();openContact(sticky)})}
    if(!document.querySelector('[data-t2-scroll-top]')){var topBtn=document.createElement('button');topBtn.className='t2-scroll-top';topBtn.type='button';topBtn.setAttribute('data-t2-scroll-top','true');topBtn.setAttribute('aria-label','Remonter en haut de la page');topBtn.textContent='↑';document.body.appendChild(topBtn);function toggleTop(){topBtn.classList.toggle('is-visible',window.scrollY>520)}window.addEventListener('scroll',toggleTop,{passive:true});toggleTop();topBtn.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});trackEvent('click_t2_scroll_top',{event_category:'engagement'})})}
    setTimeout(function(){document.querySelectorAll('.t2-question-helper,.t2-sticky-contact').forEach(function(el){el.classList.add('is-visible')});trackEvent('view_t2_question_helper',{event_category:'buyer_lead'})},900)
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addHelpers);else addHelpers();
})();
;(function(){
  if(window.__mathildeContactWidget)return;window.__mathildeContactWidget=true;
  function messageForPage(){
    var p=location.pathname;
    if(p.indexOf('vendre')!==-1||p.indexOf('estimation')!==-1||p.indexOf('prix-immobilier')!==-1)return 'Ia ora na Mathilde, je souhaite parler de mon projet immobilier à Tahiti. Peux-tu me recontacter ?';
    if(p.indexOf('acheter')!==-1||p.indexOf('biens-a-vendre')!==-1)return 'Ia ora na Mathilde, je cherche un bien à Tahiti. Peux-tu me recontacter ?';
    if(p.indexOf('t2-renove-paofai-papeete')!==-1)return 'Ia ora na Mathilde, je souhaite recevoir plus d’informations sur le T2 secteur Paofai à Papeete.';
    if(p.indexOf('appartement-t2-punaauia-pk11')!==-1)return 'Ia ora na Mathilde, je suis intéressé(e) par le T2 à Punaauia. Peux-tu me donner plus d’informations ?';
    if(p.indexOf('t2-renove-paofai-papeete')!==-1)return 'Ia ora na Mathilde, je souhaite recevoir plus d’informations sur le T2 secteur Paofai à Papeete.';
    return 'Ia ora na Mathilde, j’ai une question sur mon projet immobilier à Tahiti. Peux-tu me recontacter ?';
  }
  function addContactWidget(){
    if(document.querySelector('[data-mk-contact-widget]'))return;
    var msg=messageForPage();
    var wa='https://wa.me/33782475958?text='+encodeMessage(msg);
    var sms='sms:+68988078247?body='+encodeURIComponent(msg);
    var tel='tel:+68988078247';
    var widget=document.createElement('div');
    widget.className='mk-contact-widget';
    widget.setAttribute('data-mk-contact-widget','true');
    widget.innerHTML='<button class="mk-contact-toggle" type="button" aria-expanded="false">Me contacter</button><div class="mk-contact-panel" aria-label="Options de contact"><strong>Contacter Mathilde</strong><p>Choisis le canal le plus simple pour toi.</p><div class="mk-contact-options"><a class="whatsapp" href="'+wa+'" target="_blank" rel="noopener" data-event="click_contact_widget_whatsapp">WhatsApp</a><a class="sms" href="'+sms+'" data-event="click_contact_widget_sms">SMS</a><a class="call" href="'+tel+'" data-event="click_contact_widget_call">Appeler</a></div></div>';
    document.body.appendChild(widget);
    var toggle=widget.querySelector('.mk-contact-toggle');
    toggle.addEventListener('click',function(){
      var open=widget.classList.toggle('is-open');
      toggle.setAttribute('aria-expanded',open?'true':'false');
      trackEvent(open?'open_contact_widget':'close_contact_widget',{event_category:'contact'});
    });
    document.addEventListener('click',function(e){
      if(widget.contains(e.target))return;
      widget.classList.remove('is-open');
      toggle.setAttribute('aria-expanded','false');
    });
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addContactWidget);else addContactWidget();
})();
document.addEventListener('click',function(e){var t=e.target.closest('[data-event]');if(t)trackEvent(t.getAttribute('data-event'),{link_text:cleanText(t.textContent),link_url:t.href||''})});
document.addEventListener('DOMContentLoaded',function(){trackEvent('page_ready',{event_category:'engagement'});document.querySelectorAll('[data-t2-gallery]').forEach(function(g){var main=g.querySelector('[data-gallery-main]'),idx=g.querySelector('[data-gallery-index]'),cap=g.querySelector('[data-gallery-caption]'),thumbs=[].slice.call(g.querySelectorAll('[data-gallery-thumb]')),cur=0;if(!main||!thumbs.length)return;function show(i,src){cur=(i+thumbs.length)%thumbs.length;var th=thumbs[cur];main.style.opacity='.55';setTimeout(function(){main.src=th.getAttribute('data-full');main.alt=th.getAttribute('data-alt')||'';main.style.opacity='1'},80);if(idx)idx.textContent=String(cur+1);if(cap)cap.textContent=th.getAttribute('data-caption')||'';thumbs.forEach(function(x,n){x.classList.toggle('is-active',n===cur)});if(src)trackEvent('view_t2_gallery_photo',{event_category:'buyer_lead',gallery_index:cur+1,gallery_source:src})}g.querySelectorAll('[data-gallery-next]').forEach(function(b){b.addEventListener('click',function(){show(cur+1,'next')})});g.querySelectorAll('[data-gallery-prev]').forEach(function(b){b.addEventListener('click',function(){show(cur-1,'prev')})});thumbs.forEach(function(b,i){b.addEventListener('click',function(){show(i,'thumb')})})});document.querySelectorAll('.nav-toggle').forEach(function(btn){btn.addEventListener('click',function(){var nav=btn.closest('.nav'),m=nav&&nav.querySelector('.menu');if(!m)return;var o=m.classList.toggle('open');btn.setAttribute('aria-expanded',o?'true':'false');btn.textContent=o?'Fermer le menu':'Menu'})});var t2=document.querySelector('[data-t2-virtual-form]');if(t2)t2.addEventListener('submit',function(e){e.preventDefault();var d=new FormData(t2);var msg=['Ia ora na Mathilde, je souhaite recevoir les informations sur le T2 a Punaauia.','','Prenom : '+(d.get('prenom')||''),'Telephone : '+(d.get('telephone')||''),'Projet : '+(d.get('projet')||''),'Message : '+(d.get('message')||''),'','Je souhaite etre recontacte pour la fiche complete ou les informations utiles ou une visite privee.'].join('\n');trackEvent('submit_form_t2_virtual',{event_category:'buyer_lead'});location.href='https://wa.me/33782475958?text='+encodeMessage(msg)});var est=document.querySelector('[data-estimation-form]');if(est)est.addEventListener('submit',function(e){e.preventDefault();var d=new FormData(est);var msg=['Ia ora na Mathilde, je souhaite une estimation gratuite de mon bien a Tahiti.','','Nom : '+(d.get('nom')||''),'Telephone : '+(d.get('telephone')||''),'Email : '+(d.get('email')||''),'Commune : '+(d.get('commune')||''),'Type de bien : '+(d.get('type')||''),'Objectif : '+(d.get('objectif')||''),'Surface approximative : '+(d.get('surface')||''),'Secteur / repere : '+(d.get('adresse')||''),'Message : '+(d.get('message')||'')].join('\n');trackEvent('submit_form_estimation',{event_category:'seller_lead'});location.href='https://wa.me/33782475958?text='+encodeMessage(msg)})});

(function(){var baseTrack=window.trackEvent||trackEvent;window.trackEvent=function(n,p){p=p||{};p.page_location=location.href;p.page_path=location.pathname;p.page_title=document.title||'';var slug=document.body&&document.body.getAttribute('data-property-slug'),title=document.body&&document.body.getAttribute('data-property-title');if(slug)p.property_slug=slug;if(title)p.property_title=title;try{baseTrack(n,p)}catch(e){try{if(typeof gtag==='function')gtag('event',n,p)}catch(err){}}};try{trackEvent=window.trackEvent}catch(e){}function insertBeforeUseful(menu,a){var before=[].slice.call(menu.querySelectorAll('a')).find(function(x){return /blog|contact|suivi/i.test((x.textContent||'').trim())});menu.insertBefore(a,before||menu.lastElementChild)}function addToolsLink(menu){if(!menu||menu.querySelector('[href="/outils-immobilier-tahiti.html"]'))return;var a=document.createElement('a');a.href='/outils-immobilier-tahiti.html';a.textContent='Outils';a.setAttribute('data-event','calculator_started');insertBeforeUseful(menu,a)}function addSellerLink(menu){if(!menu||menu.querySelector('[href="/suivi-vendeur.html"]'))return;var old=menu.querySelector('[href="/demo-espace-vendeur.html"]');if(old&&/Suivi vendeur|Démo suivi vendeur/.test(old.textContent||'')){old.href='/suivi-vendeur.html';old.textContent='Suivi vendeur';old.setAttribute('data-event','click_nav_seller_access');return}var a=document.createElement('a');a.href='/suivi-vendeur.html';a.textContent='Suivi vendeur';a.setAttribute('data-event','click_nav_seller_access');insertBeforeUseful(menu,a)}document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.menu,.home-menu').forEach(function(menu){addToolsLink(menu);addSellerLink(menu)});if(document.body&&document.body.getAttribute('data-property-slug'))window.trackEvent('property_page_view',{event_category:'property'});document.querySelectorAll('[data-estimation-form]').forEach(function(f){f.addEventListener('submit',function(){window.trackEvent('contact_form_submit',{event_category:'seller_lead'})},{capture:true})});document.querySelectorAll('[data-t2-virtual-form]').forEach(function(f){f.addEventListener('submit',function(){window.trackEvent('visit_request_submit',{event_category:'buyer_lead'})},{capture:true})})});document.addEventListener('click',function(e){var a=e.target.closest('a[href]');if(!a)return;var href=a.getAttribute('href')||'';if(href.indexOf('wa.me')!==-1||href.indexOf('whatsapp')!==-1)window.trackEvent('whatsapp_clicked',{link_text:cleanText(a.textContent),link_url:a.href});if(href.indexOf('tel:')===0)window.trackEvent('phone_click',{link_text:cleanText(a.textContent),link_url:a.href})},true)})();
